### ISSUE TITLE
webpack打包问题。

### ISSUE THREAD

**Issue by WebPuY** [Nealyang/React-Express-Blog-Demo#27]
修改了webpack配置，增加了一个打包配置：、
"build": "cross-env NODE_ENV=production webpack --config webpack.prod.js"

然后执行 npm run build。报错如下

ERROR in ./app/index.js
Module build failed: ReferenceError: [BABEL] D:\yp\React-Blog-Demo\app\index.js: Unknown option: D:\yp\React-Blog-Demo\.babelrc.env.production.preset. Check out http://babeljs.io/docs/usage/options/ for more information about options.

**# _A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:_**

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.
    at Logger.error (D:\yp\React-Blog-Demo\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (D:\yp\React-Blog-Demo\node_modules\babel-core\lib\transformation\file\options\option-manager.js:226:20)
    at OptionManager.init (D:\yp\React-Blog-Demo\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\yp\React-Blog-Demo\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\yp\React-Blog-Demo\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\yp\React-Blog-Demo\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\yp\React-Blog-Demo\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (D:\yp\React-Blog-Demo\node_modules\babel-loader\lib\index.js:173:20)
 @ multi babel-polyfill ./app/index.js

**Comment by WebPuY** [comment]
https://github.com/babel/babel-loader/issues/173

**Comment by WebPuY** [comment]
bablerc里面的env配置，导致生产打包失败。

**Comment by WebPuY** [comment]
babelrc的"presets": ["es2015","react","stage-0", "env"],删掉‘env’就可以了。

**Comment by WebPuY** [comment]
作者你好，我补充了生产环境打包构建的代码，没几行，已经在本地跑过，想merge到你的项目里面，可以吗？

**Comment by Nealyang** [comment]
好啊~你提一下pr
